version: '3'

services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_SITE_URL: http://localhost:82
    volumes:
      - ./src/wp-content/themes:/var/www/html/wp-content/themes
      - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./docker/wordpress/wp-config.php:/var/www/html/wp-config.php:ro

  redis:
    image: redis

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

  varnish:
    image: varnish
    ports:
      - "82:80"
    volumes:
      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node